### ISSUE TITLE
Improve graph guide source block rendering

### ISSUE THREAD

**Issue by Mogztter** [neo4j/neo4j-browser#1536]
### Description

Source blocks that contain relatively long lines are hard to read.
The first issue is that lines are misaligned because of the "play button"

![not-so-good](https://user-images.githubusercontent.com/333276/134527500-d7e77cbd-9e0c-4ab3-9d00-0acd32d2f79a.png)

As you can seen, the first line is misaligned with the other lines.
The second issue is that we are using line wrap on `.slide code`. We should not use `white-space: pre-wrap;` when the `<code>` element is inside a `<pre>` element.

### Reproduce Steps

Run the following command in Neo4j browser:

```
:guide https://guides.neo4j.com/graph-examples/bank-fraud-detection/graph_guide
```

Browse to slide 7 "Entity Link Analysis".

### Expected Behavior

We can use an absolute positioning on the "play button" and remove line wrap. Here's the result:

![image](https://user-images.githubusercontent.com/333276/134528079-4a528703-1a70-44ad-b064-798c987c6608.png)

### Can you propose a solution?

```css
.slide pre code {
  white-space: pre;
  padding-left: 0;
}

pre > .fa.fa-play-circle-o {
  padding-right: 4px;
  left: 20px;
}

.slide pre.code {
  padding-left: 20px !important;
}
```

### Your Environment

Neo4j Browser version: 4.3.4
