### ISSUE TITLE
ETL tool in neo4j browser

### ISSUE THREAD

**Issue by abalter** [neo4j/neo4j-browser#1539]
How do I install the ETL tool in neo4j server? The browser does not have the plugin symbol the way the desktop version does.

**Comment by test123-all** [comment]
Hello @abalter,
I don't know if your problem is already solved but if you have access to your neo4j server and you are running it with docker you can add a volume for the plugins.

If you use docker-compose you can add the line `- /YOURPATH/neo4j-data/plugins:/plugins` to the volumes-section of your docker-compose.yml file. An example could look like this:

```
# Docker Compose file

version: '3.7'

services:
  neo4j:
    image: neo4j
    restart: unless-stopped
    container_name: neo4jcontainer
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /YOURPATH/neo4j-data:/data
      - /YOURPATH/neo4j-data/logs:/logs
      - /YOURPATH/neo4j-data/plugins:/plugins  # Please note this line

```
You have probably got a .jar file(your plugin) that you can drop in the directory under: `/YOURPATH/neo4j-data/plugins`.
At least for the APOC-plugin it is a .jar file.  
<br/>

Hope that helps
